### ISSUE TITLE
Cannot add badges to collections via UI

### ISSUE THREAD

**Issue by ottonomy** [mozilla/openbadges-backpack#1058]
Dragging a badge onto a collection does nothing, and produces no errors in the console.

Tested by @dpresant in Firefox and Chrome. I reproduced it in Chrome. I can't remember which element was supposed to be draggable (was it just the image <IMG> itself? ), but I don't see any draggable attributes on any element.

Probably unrelated, but there is a 404 for a javascript file occurring for http://backpack.openbadges.org/js/nunjucks-templates.js 

Also, the site is not forcing HTTPS by default.

**Comment by jbuck** [comment]
@ottonomy Looks like that was related, because after fixing it in https://github.com/mozilla/openbadges-backpack/commit/34140750f5c0c460f6e0be3333eeee1e01192612 I am now able to drag and drop badges. Good catch!

I also forced HTTPS in https://github.com/mozilla/openbadges-backpack/commit/0ef69c7085806e3db0455b2df5f90f9c2b2e4a97 and https://github.com/mozilla/openbadges-backpack/commit/329541eded8fc8e490afb44e1c157ed528bd0e36
