### ISSUE TITLE
Can't move SUMO badges to Backpack

### ISSUE THREAD

**Issue by mattdigitalme** [mozilla/openbadges-backpack#1083]
There's no way for me to move my badges from https://support.mozilla.org/en-US/user/alex_mayorga/ to https://backpack.openbadges.org/ =(

**Comment by mattdigitalme** [comment]
cc @alex-mayorga

**Comment by mattdigitalme** [comment]
@auralon Are these even Open Badges? https://support.mozilla.org/en-US/badges/

**Comment by auralon** [comment]
@mattdigitalme all that would be needed to get these in the Backpack is a publicly available assertion.

**Comment by mattdigitalme** [comment]
hmmmm - who do we contact about getting this done? @auralon

**Comment by auralon** [comment]
@mattdigitalme, good question! @simonwex might know.

There may well be assertions already hosted, but I'm not sure.  I wonder what process the users are going through in order to try to import these badges into the Backpack.

If they try to upload the images, then they will fail if they do not contain baked in badge metadata.

It doesn't look like the site in question hooks into the Backpack using the Issuer or Connect API.  If the site begins to use those integration methods, then they would need to provide hosted assertions also.

**Comment by mattdigitalme** [comment]
The guy I spoke to at Mozfest and where this issue was created said there was no way in the system to push to Backpack and as you say, downloading and importing proved fruitless - I'll try and see if I can find out who looks after SUMO @auralon
