### ISSUE TITLE
Password reset email addresses not getting through

### ISSUE THREAD

**Issue by mattdigitalme** [mozilla/openbadges-backpack#1133]
Hey @cadecairos could we be hitting the same issue with this one as we were with some migration emails not getting through. How best for you to look into it - get you a copy of specific email adds again that are not receiving the mail?

Cheers :)

**Comment by cadecairos** [comment]
I took a look at the Mailgun logs and I see a handful of reasons for delivery failure:

1. emails to the receiver keep bouncing, so Mailgun refuses to send until a cooldown period expires
2. The receiver's email inbox is over-quota, so the mail is rejected
3. The receiver's mail system rejected the email because it distrusts Mailgun's Mailservers
4. The Mailgun IP was blacklisted by the receiving party's provider
5. The email address can't be found by the receiving mail system

All of these delivery failures were tied to attempts to reset passwords.

**Comment by mattdigitalme** [comment]
OK cool thanks @cadecairos so all of these are on the user end if I'm reading correctly? I'll get them to look into things with their system admins :)

Thanks

M
