### ISSUE TITLE
initial trouble with web hacking badge login

### ISSUE THREAD

**Issue by ftrotter** [mozilla/openbadges-backpack#1151]
Why is there no signup page on the demo badges page?

https://screencast.com/t/i86KBNilQY

**Comment by mattdigitalme** [comment]
The layer that appears when you try to push a badge to the BP has not been built with a signup option integrated within - this is because you would need to navigate more than one page and essentially run a browser window in that pop. The best option is to create an account first then attempt to re-push - convoluted I know, but currently the way this is set up.

Matt

**Comment by mattdigitalme** [comment]
Just to add to this, you can get to a signup option in this layer by clicking the 'I am not" option if you are already logged in to the Backpack before you push a badge. You'll then be able to see the navigation issues I mentioned above.
